sensor:
  - platform: rest
    resource: https://www.cbr-xml-daily.ru/daily_json.js
    name: USD_RUR
    value_template: "{{ value_json.Valute.USD.Value | float(0) | round(2, 'common' ,0) }}"
    unit_of_measurement: "RUR"
    scan_interval: 1200

  - platform: rest
    resource: https://www.cbr-xml-daily.ru/daily_json.js
    name: EUR_RUR
    value_template: "{{ value_json.Valute.EUR.Value | float(0) | round(2, 'common' ,0) }}"
    unit_of_measurement: "RUR"
    scan_interval: 1200