# счетчик проверки доступности сервера HA

counter:
# счетчик работы home assistant в минутах
  ha_counter:
    initial: 0
    step: 1
    icon: mdi:counter
# uptime после перезагрузки homeassistant
  ha_uptime:
    initial: 0
    step: 1
    icon: mdi:power-cycle
    restore: false
# счетчик ошибок в homeassistant
  error_counter:
    name: Errors
    icon: mdi:alert
sensor:
  - platform: template
    sensors:
      ha_motocounter_hour:
        friendly_name: "Счетчик работы сервера в часах"
        icon_template: mdi:counter
        unit_of_measurement: 'ч.'
        value_template: >
          {% set uptime_hour = (states('counter.ha_counter') |int / 60) | round (1) %}
            {{uptime_hour}}
      ha_work_time:
        friendly_name: "Время работы сервера"
        icon_template: mdi:clock-digital
#        unit_of_measurement: 'Время работы'
        value_template: >
          {% set uptime = states('counter.ha_counter') | int %}
          {% set minutes = ( uptime % 60) | int %}
          {% set hours = ((uptime % 1440) /60) | int %}
          {% set days = (uptime / 1440) | int %}
            {% if uptime < 1 %}
              Меньше минуты
            {% else %}
              {% if days > 0 %}
                {{ days }} д.
              {% endif %}
              {% if hours > 0 %}
                {% if days > 0 %}
                  {{' '}}
                {% endif %}
                {{ hours }} ч.
              {% endif %}
              {% if minutes > 0 %}
                {% if days > 0 or hours > 0 %}
                  {{' '}}
              {% endif %}
                {{minutes}} мин.
              {% endif %}
            {% endif %}
