# @to4ko
# https://github.com/to4ko/myconfig/blob/master/my_config/sensors/ha_versions.yaml
# ############################################################################
# HA Installed version sensor
# # ############################################################################
sensor:
#   - platform: version
#     name: HA Installed Version
#     scan_interval: 1800

# ############################################################################
# HA Latest version sensor
# ############################################################################
  # - platform: rest
  #   resource: https://version.home-assistant.io/stable.json
  #   name: HA Latest Version
  #   value_template: "{{ value_json.homeassistant.default }}"
  #   scan_interval: 1800

  # - platform: rest
  #   resource: https://version.home-assistant.io/beta.json
  #   name: HA Latest Beta
  #   value_template: "{{ value_json.homeassistant.default }}"
  #   scan_interval: 1800

# ############################################################################
# HA Latest Supervisor version
# ############################################################################
  - platform: rest
    resource: https://version.home-assistant.io/stable.json
    name: HA Supervisor Latest Version
    value_template: "{{ value_json.supervisor }}"
    scan_interval: 1800

  - platform: rest
    resource: https://version.home-assistant.io/beta.json
    name: HA Supervisor Latest Beta
    value_template: "{{ value_json.supervisor }}"
    scan_interval: 1800