recorder:
  db_url: !secret recorder_db
#  purge_keep_days: 3
#  auto_purge: false
# purge_interval: 7
  commit_interval: 30
  include:
    domains:
      - sensor
      - switch
      - shell_command
      - binary_sensor
      - input_text
      - light
      - script
      - device_tracker
      - person      
  exclude:
    domains:
      - alarm_control_panel
      - camera
      - persistent_notification
      - zone
      - sun
    entities:
      - sensor.time
    entity_globs: 
      - sensor.*_zigbee 
      - sensor.*_ble
    event_types:
      - service_removed
      - service_executed
      - platform_discovered
      - homeassistant_start
      - homeassistant_stop
      - feedreader
      - service_registered
      - call_service
      - component_loaded
      - logbook_entry
      - system_log_event
      - automation_triggered
      - script_started
      - timer_out_of_sync

# размер бд mariadb
sensor:
  - platform: sql
    db_url: !secret recorder_db
    queries:
      - name: DBsize
        query: 'SELECT table_schema AS "homeassistant", Round(Sum(data_length + index_length) / 1024 / 1024, 1) "value" FROM information_schema.tables WHERE table_schema="homeassistant" GROUP BY table_schema;'
        column: 'value'
        unit_of_measurement: MB
    scan_interval: 60

  # - platform: filesize
  #   file_paths:
  #     - /config/home-assistant.log

# DB size sensors - Speed
  - platform: statistics
    entity_id: sensor.DBsize
    name: DBsize_statistics
    sampling_size: 20000
    state_characteristic: mean
    max_age:
      minutes: 60