sensor:
############ Сенсор времени ############
  - platform: time_date
    display_options:
      - "time"  # время
      - "date"  # дата  

# binary_sensor:
#   - platform: template
#     sensors:
#       phone_alarm:
#         friendly_name: "Phone Alarm"
#         value_template: >-
#           {{ now().strftime("%a %h %d %H:%M %Z %Y") == (((state_attr('sensor.mi9t_next_alarm', 'Time in Milliseconds') | int(0) / 1000) + 0 * 60 ) | timestamp_custom('%a %h %d %H:%M %Z %Y')) }}

template:
  - binary_sensor:
    - name: phone_alarm
      unique_id: phone_alarm
      state: >
        {{ now().strftime("%a %h %d %H:%M %Z %Y") == (((state_attr('sensor.mi_9t_next_alarm', 'Time in Milliseconds') | int(0) / 1000) + 3600 ) | timestamp_custom('%a %h %d %H:%M %Z %Y')) }}
      icon: mdi:alarm-check
      availability: >-
        {{ states('sensor.mi_9t_next_alarm') != 'unavailable' }}
      attributes:
        alarm_time: >-
            {{ ((((state_attr('sensor.mi_9t_next_alarm', 'Time in Milliseconds') | int(0) / 1000)) + 3600) | timestamp_custom('%a %h %d %H:%M %Z %Y')) }}
  
  - sensor:
    - name: "mi_9t_next_alarm_correction"
      unique_id: "mi 9t next alarm correction"
      state: > 
        {{ ((((state_attr('sensor.mi_9t_next_alarm', 'Time in Milliseconds') | int(0) / 1000)) + 3600) | timestamp_custom('%a %h %d %H:%M %Z %Y')) }}