binary_sensor:
#рабочие дни
  - platform: workday
    country: RU

  - platform: tod
    name: Dark Outside
    after: sunset
    after_offset: '00:40'
    before: sunrise
    before_offset: '-01:00'

  - platform: tod
    name: Light Outside
    after: sunrise
    after_offset: '-00:59'
    before: sunset
    before_offset: '01:30'

  - platform: tod
    name: tod_day
    after: '07:30'
    before: '20:00'

  - platform: tod
    name: tod_day_non_working
    after: '10:00'
    before: '20:00'

  - platform: tod
    name: tariff_t1
    after: '07:00'
    before: '23:00'
      
  - platform: tod
    name: tariff_t2
    after: '23:00'
    before: '07:00'

  - platform: tod
    name: tod_astro_day
    after: sunrise
    before: sunset
    #    icon: >
#      {% if is_state('binary_sensor.dark_outside','off') %}
#      mdi:brightness-5
#      {% else %}
#      mdi:weather-night
#      {% endif %}

# время включения автоматического контроля света
  - platform: tod
    name: auto_light_time
    after: '23:00:00'
    before: sunrise
    before_offset: '00:40'

