substitutions:
  board_name: doorbell
 
esphome:
  name: ${board_name}
  comment: Sonoff Mini doorbell
  
esp8266:
  board: esp8285
  esp8266_restore_from_flash: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: true

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ring Hotspot"
    password: !secret wifi_pass

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  reboot_timeout: 0min
  
ota:
  
globals:
  - id: mute_mode
    type: bool
    initial_value: 'false'
  - id: short_mode
    type: bool
    initial_value: 'false

text_sensor:
  - platform: template
    name: ${board_name}_Uptime
    lambda: |-
        int seconds = round(id(uptime_sensor).raw_state);
        int days = seconds / (24 * 3600);
        seconds = seconds % (24 * 3600);
        int hours = seconds / 3600;
        seconds = seconds % 3600;
        int minutes = seconds /  60;
        seconds = seconds % 60;
        return (
          (days ? to_string(days) + "d " : "00d ") +
          (hours ? to_string(hours) + "h " : "00h ") +
          (minutes ? to_string(minutes) + "m " : "00m ") +
          (to_string(seconds) + "s")
        );
    icon: mdi:clock-start
    update_interval: 15s

  - platform: wifi_info
    ip_address:
      name: ${board_name}_IP
    ssid:
      name: ${board_name}_SSID
    bssid:
      name: ${board_name}_BSSID
    mac_address:
      name: ${board_name}_Mac
    scan_results:
      name: ${board_name}_Latest_Scan_Results

  - platform: version
    name: ${board_name}_ESPHome_Version
    hide_timestamp: true

sensor:
  - platform: uptime
    name: ${board_name}_Uptime_s
    id: uptime_sensor
    update_interval: 15s

  - platform: wifi_signal
    name: ${board_name}_WiFi_RSSI
    update_interval: 60s    

button:
  - platform: restart
    name: ${board_name}_Restart
    id: restart_button



binary_sensor:
// internal button (кнопка на sonoff)
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: ring_btn0
 // клик по кнопке переключает состояние звонка 
    on_click:
      - min_length: 50ms
        then:
          - switch.toggle: ring_relay
 // SW button (внешняя кнопка звонка)
  - platform: gpio
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    name: ring_btn04
    on_press:
      then:
        if:
          condition:
            - switch.is_off: mute
          then:
            - switch.turn_on: ring_relay
            if:
              condition:
                - switch.is_on: short_ring
              then:
                delay (300)
                - switch.turn_off: ring_relay
    on_release:
      then:
        - switch.turn_off: ring_relay
    filters:
      - delayed_on_off: 50ms
  - platform: status
    name: ring_status

status_led:
  pin:
    number: GPIO13
    inverted: True
    
switch:
  - platform: gpio
    id: ring_relay
    name: "ring_relay"
    pin: GPIO12
    restore_mode: ALWAYS_OFF
   
  - platform: template
    name: ${board_name}_Mute
    id: mute
    icon: mdi:volume-off
    optimistic: true
    restore_state: true
    lambda: |-
      return id(mute_mode)    
    on_turn_on:
      - globals.set:
          id: mute_mode
          value: 'true'
    on_turn_off:
      - globals.set:
          id: mute_mode
          value: 'false'
      - switch.turn_off: ring_relay
      
   - platform: template
    name: ${board_name}_short_ring
    id: short_ring
    icon: mdi:bell-sleep-outline
    optimistic: true
    restore_state: true
    lambda: |-
      return id(short_mode)    
    on_turn_on:
      - globals.set:
          id: mute_mode
          value: 'true'
    on_turn_off:
      - globals.set:
          id: mute_mode
          value: 'false'
      - switch.turn_off: ring_relay
time:
  - platform: sntp
    id: sntp_time
    timezone: UTC-3
